language: java

sudo: required

env:
  # Give Maven 1GB of memory to work with
  - MAVEN_OPTS=-Xmx2048M
  
services:
  - docker
  
before_install:
  # - setup_docker.sh
  - docker-compose rm -f
  - docker-compose pull

script: 
  # docker needs jar file to start
  - mvn clean test package
  - docker-compose build
  - docker-compose up -d
  - sleep 120 # wait that containers are ready
  - docker-compose logs workers
  - docker-compose logs rabbitmq
  - docker-compose ps
  - docker-compose top
  - mvn integration-test -P integration-test
  
after_script:
  - docker-compose stop -t 1