language: java
jdk:
  - oraclejdk8

sudo: required

env:
  # Give Maven 2GB of memory to work with
  - MAVEN_OPTS=-Xmx2048M
  
services:
  - docker
  
before_install:
  - mvn install:install-file -Dfile=lib/ftm-api-2.4.2.jar -DgroupId=oracle.cloudstorage.ftm -DartifactId=ftm-api -Dversion=1.0 -Dpackaging=jar
  - mvn install:install-file -Dfile=lib/low-level-api-core-1.14.19.jar -DgroupId=oracle.cloudstorage.ftm -DartifactId=low-level-api-core -Dversion=1.0 -Dpackaging=jar
  - docker-compose rm -f

script:
  # Run maven unit test
  - mvn clean test
  # Start required services
  - docker-compose up -d rabbitmq mysql vault vault-administration
  # Check everything is running as expected
  - sleep 60 # wait that container is ready
  # Make sure rabbitmq is running properly
  - docker-compose logs rabbitmq
  - docker-compose exec rabbitmq rabbitmqctl authenticate_user datavault datavault
  # Build the workers container and run
  - sudo docker-compose up -d --build workers
  # Delete unused containers
  - docker-compose rm -f maven-build
  - docker-compose rm -f vault-administration
  # Check everything is running as expected
  - sleep 60 # wait that container is ready
  - docker-compose logs workers
  - docker-compose ps
  # Run integration tests
  - mvn verify -P integration-test
  - sed -i 's/chunking\.enabled = true/chunking.enabled = false/' docker/config/datavault.properties
  - docker-compose restart workers
  - mvn verify -P integration-test
  - sed -i 's/encryption\.enabled = true/encryption.enabled = false/' docker/config/datavault.properties
  - docker-compose restart workers
  - mvn verify -P integration-test
  - sed -i 's/chunking\.enabled = false/chunking.enabled = true/' docker/config/datavault.properties
  - docker-compose restart workers
  - mvn verify -P integration-test
  
after_script:
  - docker-compose stop -t 1
