version: "3.7"
services:
  db:
    container_name: dv-byodb-mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "test" #same name of db in 'backup.sql'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "user"
      # You can use whatever password you like
      MYSQL_PASSWORD: "userpass"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "rootpass"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
    volumes:
      - v-local-byodb-mysql:/var/lib/mysql
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
volumes:
  v-local-byodb-mysql: